* COCA：6366 发音 附注 例句Unit28   恋练有词-1575   Collins
* 高中 CET4 CET6 考研 TOEFL IELTS GRE   
acquaintance
美 [ə'kwentəns] 英 [ə'kweɪnt(ə)ns]
n.认识; 熟人;了解
have an acquaintance with someone 与……某人相识
make one's acquaintance 结识某人
A person of one's acquaintance 所认识的 
熟人(47%)，相识(33%)，了解(20%)
柯林斯词典★★☆☆☆   
n.认识的人；泛泛之交
An acquaintance is someone who you have met and know slightly, but not well.
  [oft with poss]
n.认识；相识
If you have an acquaintance with someone, you have met them and you know them.
  [oft poss N]
n.了解；熟悉
Your acquaintance with a subject is your knowledge or experience of it.
  [usu with supp] [FORMAL 正式]
phrase.与（某人）初次相识；结识(某人)
When you make someone's acquaintance, you meet them for the first time and get to know them a little.
  [V inflects] [FORMAL 正式]
phrase.所认识的
A person of your acquaintance is someone who you have met and know.
  [n PHR] [FORMAL 正式]
同义词辨析
acquaintance, pal, mate, friend
这组词都有“朋友”的意思，其区别是：
[[acquaintance]]: 指彼此相识，但交往不甚密切，相互间没有深厚情感的人。
[[pal]]: 口语用词，指十分要好的朋友。
[[mate]]: 最普通用词，既可指好友、同事，又可指合伙人，还可指配偶的一方。
[[friend]]: 一般用词，指某人喜爱并乐意与之相交往的人。
同根词派生
词根：acquaint
* adj.
* acquainted 熟识的；知晓的；有知识的
* n.
* acquaintanceship 认识；相识；交往关系
* v.
* acquainted 使了解（acquaint的过去分词）
* vt.
* acquaint 使熟悉；使认识
*