* COCA：6489 发音 附注 例句Unit26   恋练有词Collins
* CET4 CET6 考研 TOEFL IELTS GRE   
cement
美 [sə'mɛnt] 英 [sɪ'ment]
n.水泥;胶合剂 vt.巩固,加强;使黏合[-ed]
concrete混凝土
词源： cement 水泥 → 来自PIE*skei,砍，劈，词源同excise,scissor .-ment,名词后缀。原指劈下的小石块，后指水泥。
释义：水泥(93%)，巩固(3%)，用水泥涂(1%)，纽带(1%)，接合剂(1%)，基石(1%)
词性：名词(76%), 动词(24%)
柯林斯词典★★☆☆☆   
n.水泥
Cement is a grey powder which is mixed with sand and water in order to make concrete.
n.同 concrete
Cement is the same as concrete .
n.胶接剂；接合剂
Glue that is made for sticking particular substances together is sometimes called cement .
  [usu n N]
verb.巩固；加强
Something that cements a relationship or agreement makes it stronger.
  [V n]
n.起巩固作用的因素；加强剂；纽带
The cement of a relationship or agreement is something that makes it stronger and more long-lasting.
  [usu with supp] [LITERARY 文]
verb.把…黏合；使黏结
If things are cemented together, they are stuck or fastened together.
  [be V-ed prep/adv] [usu passive]
同义词辨析
enhance, cement, strengthen
[[enhance]]: 使…看起来更好；提高；美化
[[cement]]: （比喻）将…结合在一起；加强；巩固。如cement a friendship表示“加强友谊”
[[strengthe]]n: 使…更强
词派生
词根：cement
* adj.
* cementitious 胶结的，有粘结性的；似水泥的
* cemental 白垩质的