* COCA：2495 发音 附注 例句Unit25   恋练有词-1575   Collins
* CET4 CET6 考研 TOEFL IELTS GRE   
embrace
美 [ɪm'bres] 英 [ɪm'breɪs;em-]
vt.拥抱;包括;接受 n.拥抱,怀抱
hug
词源： embrace 拥抱 → em-,进入，使，brace,胳膊，箍子。
释义：拥抱(64%)，接受(25%)，信奉(5%)，包含(4%)，包围(2%)
词性：动词(84%), 名词(16%)
柯林斯词典★★☆☆☆   
v.抱；拥抱
If you embrace someone, you put your arms around them and hold them tightly, usually in order to show your love or affection for them. You can also say that two people embrace .
  [V n (non-recip)] [pl-n V] [usu with supp]
verb.欣然接受，支持（变革、政治体制、观点等）
If you embrace a change, political system, or idea, you accept it and start supporting it or believing in it.
  [V n] [FORMAL 正式]
verb.包括；接纳
If something embraces a group of people, things, or ideas, it includes them in a larger group or category.
  [V n] [FORMAL 正式]
同义词辨析
hold, contain, involve, embrace, comprise, comprehend, include
这组词都有“包括，包含”的意思，其区别是：
[[hold]]: 常和contain换用。指能够容纳或有足够的容纳量。强调包容能力。
[[contain]]: 普通用词，所涉及的物体常常是其组成部分或内容。强调包容关系。既可指具体有形的东西，也可指抽象无形的东西。
involve: 把包含因整体的性质决定的成分或结果。所包括的往往是无形的，不可触知的东西，多用作引申。
embrace: 正式用词，指把某事物纳入整个之中。
comprise: 书面用词，暗指一个整体包括不同部分所组成，可与include交换使用。
comprehend: 正工用词，指包含在整体范围以内。
include: 普通用词，指一整体包含着各独立的部分，也指某东西包含另一东西的某一部分。
同根词派生
词根：embrace
* n.
* embracing 拥抱
* embracement 拥抱；环绕；领会
* v.
* embracing 拥抱，包含（embrace的现在分词形式）