* COCA：1243 发音 附注 例句Unit21   恋练有词-Collins
* 高中 CET4 CET6 考研 TOEFL IELTS GRE   
handle
美 ['hændl] 英 ['hænd(ə)l]
vt.处理,应付;负责;操纵 n.把手
tackle cope operate
词源： handle 控制，操纵 → 来自hand,手，-le,工具格后缀。引申词义操纵，比较manipulate.
释义：处理(46%)，柄(31%)，把手(15%)，操作(5%)，触(1%)，对待(1%)，买卖(1%)
词性：动词(81%), 名词(19%)
柯林斯词典★★★★☆   
n.（门上的）拉手，把手
A handle is a small round object or a lever that is attached to a door and is used for opening and closing it.
n.（工具、包、杯等的）柄，把手，提手
A handle is the part of an object such as a tool, bag, or cup that you hold in order to be able to pick up and use the object.
verb.有能力应付；（成功地）处理
If you say that someone can handle a problem or situation, you mean that they have the ability to deal with it successfully.
  [V n]
verb.（以…方式）应付，处理
If you talk about the way that someone handles a problem or situation, you mention whether or not they are successful in achieving the result they want.
  [V n adv]
handling
The family has criticized the military's handling of Robert's death.
罗伯特的家人批评军方对罗伯特死亡的事情处理失当。
verb.负责（某项工作）
If you handle a particular area of work, you have responsibility for it.
  [V n]
verb.使用，操纵（武器、车辆等）；训练，使唤（动物）
When you handle something such as a weapon, vehicle, or animal, you use it or control it, especially by using your hands.
  [V n]
verb.（车辆等容易）操纵，驾驶
If something such as a vehicle handles well, it is easy to use or control.
  [V adv/prep]
verb.拿；抓；搬动
When you handle something, you hold it or move it with your hands.
  [V n]
n.（理解、解决问题的）方法，途径
If you have a handle on a subject or problem, you have a way of approaching it that helps you to understand it or deal with it.
  [a N on n] [INFORMAL 非正式]
phrase.大发脾气；勃然大怒
If you fly off the handle, you suddenly and completely lose your temper.
  [V inflects] [INFORMAL 非正式]
同义词辨析
deal with, cope with, dispose of, manage, handle
这些动词或短语动词都含有“处理”，“对付”之意。
[[deal with]]: 既可指处理具体事情，也可指处理或解决具有抽象意义的问题。
[[cope with:]] 指成功地处理或对付更为重大，更为严重的问题或事物。
[[dispose of]]: 与deal with同义，普通用法。
[[manage]]: 指处理日常事务与工作，也可指经营管理。
handle: 从原义“手柄”，转引申为作“处理”解时，其内涵是管理和操纵。
同根词派生
词根：handle
* adj.
* handling 操作的
* handled 有把手的；有把柄的
* n.
* handling 处理
* handler 处理者；管理者；拳击教练；（犬马等的）训练者
* v.
* handling 负责；对待（handle的ing形式）；触摸
* handled 使用；负责；触摸；指挥（handle的过去分词）