* COCA：2642 发音 附注 例句Unit15   恋练有词-Collins
* CET4 CET6 考研 TOEFL IELTS   
label
美 [ˈlebəl] 英 ['leɪb(ə)l]
n.标签,标记;称号 vt.贴标签于;把…称为
tag
词源： label 标签 → 来自PIE*leb,撕开，词源同lap,lapel,进一步来自PIE*skel,砍，撕，词源同shell, scissor.原义为撕开的小布条，后用于指用布条标签。拼写演变比较locus,ring.
释义：标签(83%)，标记(7%)，唱片公司(3%)，称号(3%)，贴标签于(3%)，把 ... 归类(1%)
词性：名词(61%), 动词(39%)
柯林斯词典★★★☆☆   
in AM, use 美国英语用 labeling, labeled
n.标签；签条；标贴
A label is a piece of paper or plastic that is attached to an object in order to give information about it.
verb.贴标签于；用标签标明
If something is labelled, a label is attached to it giving information about it.
  [be V-ed] [V-ed quote] [V-ed with n] [usu passive]
verb.（不公平地）把…称为，把…列为
If you say that someone or something is labelled as a particular thing, you mean that people generally describe them that way and you think that this is unfair.
  [be V-ed as n] [be V-ed as adj] [be V-ed n] [be V-ed adj] [usu passive] [disapproval]
n.（批评性的）标签，称号
If you say that someone gets a particular label, you mean that people show disapproval of them by describing them with a critical word or phrase.
  [usu with supp]
n.唱片公司
You can refer to a company that produces and sells CDs as a particular label .
  [usu supp N]
同义词辨析
[[tag]], label
这组词都有“标签”的意思，其区别是：
[[tag]]: 多指临时系上的标签。
[[label]]: 指上面标明货主姓名、地址及货物名称、重量、尺寸等内容的标签。
* [[at lenth]]
* [[cement]]
* [[suitable]]
*