* COCA：1604 发音 附注 例句Unit13   恋练有词-1575   Collins
* 高中 CET4 CET6 考研 TOEFL IELTS   
obtain
美 [əb'ten] 英 [əb'teɪn]
vt.获得 vi.存在
attain
词源： obtain 得到，获得 → ob-,向前，朝向，-tain,伸，抓，词源同contain,tenure.引申词义得到，获得。
获得(68%)，得到(23%)，流行(4%)，存在(3%)，通用(2%)
柯林斯词典★★★☆☆   
verb.得到；获得；实现
To obtain something means to get it or achieve it.
  [V n] [FORMAL 正式]
verb.存在；流行；通行
If a situation obtains, it exists.
  [V] [FORMAL 正式]
同义词辨析
acquire, obtain, get, secure, win, earn, gain
这组词都有“获得、取得、得到”的意思，其区别是：
acquire: 强调通过不断的、持续的努力而获得某物，也指日积月累地渐渐地获得。书面语用词。
obtain: 较正式用词，着重通过巨大努力、要求而得到所需或盼望已久的东西。
get: 普通用词，使用广泛，可指以任何方式得到某物，也不一定要经过努力。
secure: 强调要通过努力或竞争，或需要付出代价才能获得所渴望的东西。
win: 主要指通过努力、斗争、比赛等而获得胜利。
earn: 侧重指依靠自己的劳动或因付出代价与有功而获得。
gain: 侧重指经过努力或有意识行动而取得某种成就或获得某种利益或好处。
* attain, acquire, obtain, secure, achieve, earn, gain
这组词都有“获得，取得”的意思，其区别是：
attain: v.指经过不懈的努力获得未曾预料到的结果；也可指达到某一目标。
 • The salesperson attained his sales goal for the month.   这名销售员完成了当月的销售目标。
[[acquire]]: v.多指经过努力逐步获得才能、知识、习惯等，也可用于对财物等的获得，该词强调"一经获得就会长期持有"的含义。
 • It is through learning that the individual acquires many habitual ways of reacting to situations.   正是通过学习，个人才得以获得应付各种情况的习惯做法。
[[obtain]]: v.获得，买到，用于正式语体中。
 • He obtained the property with a bank loan.   他通过向银行贷款买下了那份房产。
[[secure]]: v.得到；把……拿到手，含有肯定占有难以得到的东西之意；使安全，保卫；作形容词比较常见，意为"安全的"。
 • A million signatures have been secured.   已征集到了100万人的签名。
 • He secured the office before leaving it for the night.   他晚上离开前锁好了办公室的门窗。
achieve: v.得到，获得，多指成就、目标、幸福的取得。
 • The movie star achieved success and wealth.   这个影星取得了成功和财富。
[[earn]]: v.挣得，赢得，指因工作等而得到报酬或待遇。
 • How much do you earn a week?   你一星期挣多少钱？
[[gain]]: v.指通过较大努力获得某种利益或好处；亦可指军事上的武力夺取等。
 • An investor gains by buying stocks that go up in value.   投资者通过所买股票价格上涨而得利润。
* attain, acquire, obtain, get, achieve, gain
这组词都有“获得”的意思，其区别是：
[[attain]]: 为正式用词，多用于庄重场合，主要指通过努力达到重要目的或得到珍贵的东西。如：The scientist attained great fame by a new discovery.(那科学家由于一次新发现而出了名。)
[[acquire]]: 指通过本身的努力逐渐获得知识、能力和荣誉等。如：acquire knowledge(获得知识)。
obtain: 多指凭努力或恳求得到急需或很想得到的东西。如：Howard had failed to obtain a scholarship.(霍华德没能得到奖学金。)
[[get]]: 用得最广，可指以各种方式获得各种东西。如：Where can I get enough information?(我从哪儿能得到足够的资料？)
[[achieve]]: 多指克服困难后取得胜利，成功，强调“得到”这一结果。如：He achieved his ambition in the end.(他最终实现了他的抱负。)
[[gain]]: 多指付出极大努力后获得或赢得给自己带来优势的东西。如：They gained the victory after a bloody [[battle]].(浴血奋战后他们赢得了胜利。)
* acquire, procure, obtain
acquire: 努力获得，更强调在原来基础上的自然增加
procure: 为获得某物而“小心、仔细，想出计策或施展手腕”的意思
obtain: 获得，得到
同根词派生
词根：obtain
* adj.
* obtainable 能得到的
* n.
* obtainment 获得