* COCA：1052 发音 附注 例句Unit10   恋练有词-Collins
* 高中 CET4 CET6 考研   
partner
美 ['pɑrtnɚ] 英 ['pɑːtnə]
n.伴侣,搭挡 vt.做…的搭档
mate
词源： partner 伙伴，伴侣 → 来自part,部分，-er,人。即成为其中的一部分，引申词义伙伴，伴侣。
释义：伙伴(50%)，伴侣(22%)，合伙人(14%)，搭档(13%)，同 ... 合作(1%)
词性：名词(96%), 动词(4%)
柯林斯词典★★★★☆   
n.配偶；（性）伴侣
Your partner is the person you are married to or are having a romantic or sexual relationship with.
  [oft poss N]
n.同伴；搭档
Your partner is the person you are doing something with, for example dancing with or playing with in a game against two other people.
n.合伙人
The partners in a firm or business are the people who share the ownership of it.
  [BUSINESS 商]
n.盟友；伙伴
The partner of a country or organization is another country or organization with which they work or do business.
  [usu with supp]
verb.（比赛或舞蹈中）做…的伙伴（或搭档），与…配对
If you partner someone, you are their partner in a game or in a dance.
  [V n] [be V-ed by/with n] [V n to n]
同义词辨析
comrade, companion, colleague, partner, fellow, associate
这组词都有“同事，伙伴”的意思，其区别是：
[[comrade]]: 指具有共同的事业、利益关系相一致的人。
[[companion]]: 指陪伴他人的人，即同伴或陪伴。
[[colleague]]: 一般用于对同事的正式称呼，基本上专用在职业关系上。
[[partner]]: 指事业中处于合伙关系的人，或指婚姻、游戏、跳舞中的另一方。
[[fellow]]: 多用复数形式，指一块住、生活或同行共事的人。
[[associate]]: 普通用词，侧重指在利害关系上密切相关。
同根词派生
词根：partner
* n.
* partnership 合伙；[经管] 合伙企业；合作关系；合伙契约