* COCA：1799 发音 附注 例句Unit15   恋练有词-1575   Collins
* CET4 CET6 考研 TOEFL IELTS GRE   
pursue
美 [pə'sʊ] 英 [pə'sjuː]
vt.开展,实行(carry);追逐,追赶;追问,追究;追求
conduct：进行，实施
词源： pursue 追求，追逐，探索 → 来自古法语poursuir,来自porsivre 拼写变体，来自俗拉丁语*prosequare,来自prosequi,追求，追随，跟随，追逐，来自pur-,向前，-seq,跟随，词源同sequence,prosecute,execute.
追求(81%)，从事(11%)，追捕(7%)，继续执行(1%)
柯林斯词典★★★☆☆   
verb.实行；执行；贯彻
If you pursue an activity, interest, or plan, you carry it out or follow it.
  [V n] [FORMAL 正式]
verb.寻求；追求
If you pursue a particular aim or result, you make efforts to achieve it, often over a long period of time.
  [V n] [FORMAL 正式]
verb.追查；追问；追究
If you pursue a particular topic, you try to find out more about it by asking questions.
  [V n] [FORMAL 正式]
verb.追赶；追逐；追捕
If you pursue a person, vehicle, or animal, you follow them, usually in order to catch them.
  [V n] [FORMAL 正式]
同义词辨析
pursue, trace, trail, track, hunt, chase, follow
这组词都有“跟随、追踪”的意思，其区别是：
[[pursue]]: 指坚持不懈、毫不动摇地紧跟、追赶某人、某物或某个事业。
[[trace]]: 指根据线索或足迹进行跟踪。用于抽象意义时指找到某事物的根源。
[[trail]]: 一般指跟踪追击。
[[track]]: 指沿着人或动物留下的印迹或行迹追踪。原义为“追猎、猎取”，现用于指追捕或搜寻逃犯等。
[[chase]]: 指快速追赶或决心追踪，褒义贬义均可用。
[[follow]]: 普遍用词，含义最广，多指跟随起引导作用的人或物，跟随的动机可以是善意的，也可能是恶意的。
同根词派生
词根：pursue
* adj.
* pursuant 依据的；追赶的；随后的
* adv.
* pursuant 根据；依照
* pursuantly 因此；从而
* n.
* pursuit 追赶，追求；职业，工作
* pursuing 追求；追逐；追赶
* pursuance 追求；从事；追踪；实行
* pursuer 追求者；追捕者；研究者；原告
* pursual 追赶；追踪
* v.
* pursuing 从事；追赶（pursue的ing形式）