* COCA：6527 发音 附注 例句Unit13   恋练有词1575   Collins
* CET4 CET6 考研 TOEFL IELTS GRE   
temper
美 ['tɛmpɚ] 英 ['tempə]
n.脾气,情绪;韧度 vt.调和,使缓和
词源： temper 回火，管控，调和，调节 → 来自拉丁语temperare,调节，管控，掌握火候，把控时间，来自tempus,时间，词源同temporal.比喻用法，即掌握好时间。
释义：脾气(84%)，性情(7%)，锻炼(5%)，调和(3%)，使缓和(1%)
词性：名词(68%), 动词(32%)
柯林斯词典★★☆☆☆   
n.坏脾气；暴脾气
If you refer to someone's temper or say that they have a temper, you mean that they become angry very easily.
n.情绪；心情
Your temper is the way you are feeling at a particular time. If you are in a good temper, you feel cheerful. If you are in a bad temper, you feel angry and impatient.
  [with supp]
verb.使缓和；使温和
To temper something means to make it less extreme.
  [V n with n] [V n] [FORMAL 正式]
phrase.发脾气/开始发火
If someone is in a temper or gets into a temper, the way that they are behaving shows that they are feeling angry and impatient.
  [v-link PHR]
phrase.发脾气；大发雷霆
If you lose your temper, you become so angry that you shout at someone or show in some other way that you are no longer in control of yourself.
  [V inflects]
同义词辨析
nature, complexion, personality, disposition, character, temper
这组词都有“性格、气质、性情、习性”的意思，其区别是：
[[nature]]: 指天生的、不可改变性格。
[[complexion]]: 指由思维方式、态度和情绪所决定的本质特征。
[[personality]]: 主要指一个人稳定的心理特征。
[[disposition]]: 书面用词，指人的主要爱好或思想、精神方面的重要习性、气质。也可指短暂的情绪。
[[character]]: 指对个性或人格所作出的客观评价，常常与道德有关。
[[temper]]: 指从感情方面体现出来，决定处理问题或应付形势的方式的性格或性情，这种性情可以是暂时的也可以长久的。
同根词派生
词根：temper
* adj.
* tempered 缓和的，温和的；调节的；有…气质的
* temperamental 喜怒无常的；性情的；易兴奋的
* temperance 温暖的；有节制的
* adv.
* temperamentally 气质地
* n.
* temperament 气质，性情，性格；急躁
* temperance 戒酒；节欲；（气候等的）温和
* tempering [机] 回火
* v.
* tempered 调和（temper的过去分词）
* tempering 调和（temper的ing形式）
*