* COCA：791 发音 附注 例句Unit7   恋练有词-1575   Collins
* CET4 CET6 考研 TOEFL   
wonder
美 ['wʌndɚ] 英 ['wʌndə]
v.想知道[about];惊讶於[at] n.奇事 adj.神奇的
词源： wonder 奇迹，奇观，纳闷 → 来自Proto-Germanic*wundran,奇迹，奇观，来自PIE*wen,努力，希望，希冀，词源同Venus,win,wish.引申词义幻想，奇迹，纳闷。
释义：想知道(38%)，奇迹(21%)，惊奇(14%)，怀疑(13%)，奇观(6%)，奇妙的(4%)，非凡的(2%)，惊愕(2%)
词性：动词(80%), 名词(19%), 形容词(1%)
柯林斯词典★★★★☆   
verb.感到疑惑；纳闷儿；想弄明白
If you wonder about something, you think about it, either because it interests you and you want to know more about it, or because you are worried or suspicious about it.
  [V wh] [V about n] [V with quote] [V]
verb.(对…)大为吃惊，惊叹
If you wonder at something, you are very surprised about it or think about it in a very surprised way.
  [V at n] [V that]
n.奇事；怪事
If you say that it is a wonder that something happened, you mean that it is very surprising and unexpected.
n.惊叹；惊奇；惊异
Wonder is a feeling of great surprise and pleasure that you have, for example when you see something that is very beautiful, or when something happens that you thought was impossible.
n.奇迹；奇观；奇事
A wonder is something that causes people to feel great surprise or admiration.
  [usu the N of n/-ing]
adj.神奇的；奇妙的；有奇效的
If you refer, for example, to a young man as a wonder boy, or to a new product as a wonder drug, you mean that they are believed by many people to be very good or very effective.
  [ADJ n]
phrase.昙花一现的人(或事物)；惊艳一时的人(或事物)
If you say that someone or something is a nine-day wonder or a one-day wonder, you disapprove of the fact that they are attracting so much interest and attention, because you think that their popularity will only last for a very short time.
  [v-link PHR] [disapproval]
phrase.(用于礼貌地请人做事、征求意见或打听消息时)不知…，请问…
You can say 'I wonder' if you want to be very polite when you are asking someone to do something, or when you are asking them for their opinion or for information.
  [V inflects] [politeness]
phrase.难怪；怪不得；不足为怪
If you say 'no wonder', 'little wonder', or 'small wonder', you mean that something is not surprising.
  [PHR that]
phrase.（表示找出某事的原因）难怪，怪不得
You can say 'No wonder' when you find out the reason for something that has been puzzling you for some time.
  [PHR that]
phrase.创造奇迹；产生奇迹
If you say that a person or thing works wonders or does wonders, you mean that they have a very good effect on something.
  [V inflects]
同义词辨析
[[phenomenon]], miracle, marvel, wonder
这组词都有“奇迹”的意思，其区别是：
phenomenon: 指罕见的现象或奇人、奇事。
[[miracle]]: 一般指被认为是人力所办不到的奇异之事。
[[marvel]]: 侧重异乎寻常，奇怪，从而使人好奇。
[[wonder]]: 通常指使人惊奇的事迹、人物或景观，主要指人创造的奇迹。
同根词派生
词根：wonder
* adj.
* wonderful 奇妙的；极好的
* wondering 疑惑的；觉得奇怪的
* wondrous 奇妙的；令人惊奇的；非常的
* adv.
* wonderfully 精彩地；惊人地；极好地
* wonderingly 惊讶地；觉得奇怪地
* wondrously 极其；惊奇地；非常
* n.
* wonderland 奇境，仙境；非常奇妙的地方
* wonderment 惊奇；惊叹
* v.
* wondering 想知道（wonder的ing形式）；惊奇